# This file is auto-generated by the garlic release workflow. DO NOT EDIT.
# Template source: .github/homebrew/garlic-cask.rb.tmpl
cask "garlic" do
  arch arm: "aarch64", intel: "x86_64"

  version "0.3.4"
  sha256 arm:   "3a612f870d82ac9b56994c456a4b2e3306029193b194656c0081ae1114a13442",
         intel: "465d95a4deaa8b9fbfbf635c844b644720f7b8fb1b22bdbf3772ea8a5333dda2"

  url "https://github.com/justanotherspy/garlic/releases/download/v#{version}/garlic-#{arch}-apple-darwin.tar.gz",
      verified: "github.com/justanotherspy/garlic/"
  name "garlic"
  desc "Track active coding time with Claude Code and nudge yourself to take breaks"
  homepage "https://github.com/justanotherspy/garlic"

  livecheck do
    url :url
    strategy :github_latest
  end

  binary "garlic"

  # The released binaries are not Apple-notarized, so Homebrew's quarantine
  # flag makes Gatekeeper block them as "from an unidentified developer."
  # Strip com.apple.quarantine so the binary runs after install.
  # must_succeed: false — the attribute is absent when installed with
  # --no-quarantine, and xattr -d errors on a missing attribute.
  postflight do
    system_command "/usr/bin/xattr",
                   args:         ["-dr", "com.apple.quarantine", "#{staged_path}/garlic"],
                   must_succeed: false
  end

  caveats <<~EOS
    garlic hooks into Claude Code. To install the hooks, run:
      garlic setup
  EOS

  zap trash: "~/.garlic"
end
