# This file is auto-generated by the garnish release workflow. DO NOT EDIT.
# Template source: .github/homebrew/garnish-cask.rb.tmpl in justanotherspy/garnish
cask "garnish" do
  version "0.3.1"

  on_macos do
    on_intel do
      sha256 "a7727f80503d9f84f509627665c14042f3d684976fe70da8624ace2e01b1051f"
      url "https://github.com/justanotherspy/garnish/releases/download/v#{version}/garnish-x86_64-apple-darwin.tar.gz"
    end
    on_arm do
      sha256 "fcccc4441c06c25d97d3671c0c7f8c1eea84cb5f3b2490b8df720a4108eaeefc"
      url "https://github.com/justanotherspy/garnish/releases/download/v#{version}/garnish-aarch64-apple-darwin.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "348b965284466f9166acc4ce3c6e42d56717c25a798f850cee746f0cb4a420c0"
      url "https://github.com/justanotherspy/garnish/releases/download/v#{version}/garnish-x86_64-unknown-linux-gnu.tar.gz"
    end
    on_arm do
      sha256 "98a4f9a323d392432bf6145fdbf00486b5b29cff553d6100af47509d7764b6f3"
      url "https://github.com/justanotherspy/garnish/releases/download/v#{version}/garnish-aarch64-unknown-linux-gnu.tar.gz"
    end
  end

  name "garnish"
  desc "Fast, cached, themed status line for Claude Code"
  homepage "https://github.com/justanotherspy/garnish"

  livecheck do
    url :url
    strategy :github_latest
  end

  binary "garnish"

  # The released binaries are not Apple-notarized, so Homebrew's quarantine
  # flag makes Gatekeeper block them as "from an unidentified developer."
  # Strip com.apple.quarantine so the binary runs after install.
  # must_succeed: false — the attribute is absent when installed with
  # --no-quarantine, and xattr -d errors on a missing attribute. It also
  # swallows a wrong path, so verify a real install (not just `brew fetch`)
  # at the release approval gate, before `publish` reaches the tap:
  # `xattr -p com.apple.quarantine "$(brew --prefix)/bin/garnish"` must
  # answer "No such xattr".
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr",
          args:         ["-dr", "com.apple.quarantine", "{{staged_path}}/garnish"],
          must_succeed: false
    end
  end

  caveats <<~EOS
    To hook garnish into Claude Code (statusLine in ~/.claude/settings.json), run:
      garnish install
  EOS

  zap trash: [
    "~/.config/garnish",
    "~/.garnish.toml",
    "~/.cache/garnish",
    "~/Library/Caches/garnish",
    "~/.claude/skills/garnish-statusline",
    "~/.claude/skills/garnish-feedback",
    "~/.claude/skills/garnish-submit-preset",
  ]
end
