# This file was generated by GoReleaser. DO NOT EDIT.
cask "shuck" do
  version "1.0.4"

  on_macos do
    on_intel do
      sha256 "d2c213ad8a644f03255aa6aa486a0354e394c15189b41a87bf6d48c8948f9159"
      url "https://github.com/justanotherspy/shuck/releases/download/v#{version}/shuck_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/justanotherspy/shuck/"
    end
    on_arm do
      sha256 "7ae14dcce6572e3621d22afab0edaaf4400c324d356f4f1b1a1e05d41c5492d0"
      url "https://github.com/justanotherspy/shuck/releases/download/v#{version}/shuck_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/justanotherspy/shuck/"
    end
  end

  on_linux do
    on_intel do
      sha256 "1917176757d824191a9b644bc017c7aa3344b7d86b66c994e8f5415f6ca5f2b0"
      url "https://github.com/justanotherspy/shuck/releases/download/v#{version}/shuck_#{version}_linux_amd64.tar.gz",
        verified: "github.com/justanotherspy/shuck/"
    end
    on_arm do
      sha256 "7f2b041baf6aeb52a6a08bb5c969d382e4ec792a83e8b9eb70bfe21f3203c8f2"
      url "https://github.com/justanotherspy/shuck/releases/download/v#{version}/shuck_#{version}_linux_arm64.tar.gz",
        verified: "github.com/justanotherspy/shuck/"
    end
  end

  name "shuck"
  desc "Background monitor for GitHub PR CI failures, reviews, and action pins"
  homepage "https://github.com/justanotherspy/shuck"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "shuck"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/shuck"]
    end
  end

  # No zap stanza required

end
