# This file was generated by GoReleaser. DO NOT EDIT.
cask "shuck" do
  version "0.4.0"

  on_macos do
    on_intel do
      sha256 "e1bafb1be71b56dee309c94b420e6e833a57f54723324139cb70fcd6949e643f"
      url "https://github.com/justanotherspy/shuck/releases/download/v#{version}/shuck_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/justanotherspy/shuck/"
    end
    on_arm do
      sha256 "ee669deb69f94b5b73449266f014c1e9dccdf53b1edda701ea180b965620f881"
      url "https://github.com/justanotherspy/shuck/releases/download/v#{version}/shuck_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/justanotherspy/shuck/"
    end
  end

  on_linux do
    on_intel do
      sha256 "e13928830d09e5471baf7f9f7d722f4a6ff7256848a1fdf1ec538f49d82f9055"
      url "https://github.com/justanotherspy/shuck/releases/download/v#{version}/shuck_#{version}_linux_amd64.tar.gz",
        verified: "github.com/justanotherspy/shuck/"
    end
    on_arm do
      sha256 "c7c8a04104f7d37f5080c42222f2d62d21d974d73d9a0d7dbdb0edea4e6af23f"
      url "https://github.com/justanotherspy/shuck/releases/download/v#{version}/shuck_#{version}_linux_arm64.tar.gz",
        verified: "github.com/justanotherspy/shuck/"
    end
  end

  name "shuck"
  desc "Print the exact failing CI step logs for a GitHub PR"
  homepage "https://github.com/justanotherspy/shuck"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "shuck"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/shuck"]
    end
  end

  # No zap stanza required

end
