# This file was generated by GoReleaser. DO NOT EDIT.
cask "shuck" do
  version "0.4.2"

  on_macos do
    on_intel do
      sha256 "ecabd1ef4623adbbbd6d8b019e38172b149828406d3cf2a893cd0a4a29943f79"
      url "https://github.com/justanotherspy/shuck/releases/download/v#{version}/shuck_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/justanotherspy/shuck/"
    end
    on_arm do
      sha256 "d71f4491340abda4924335db63866397cd7a34a75a51082e627bfe85a01a2970"
      url "https://github.com/justanotherspy/shuck/releases/download/v#{version}/shuck_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/justanotherspy/shuck/"
    end
  end

  on_linux do
    on_intel do
      sha256 "d0dda64fc96b713cf4fc2cff0eaa145ab642babc998ee6007899d39c0844ddfa"
      url "https://github.com/justanotherspy/shuck/releases/download/v#{version}/shuck_#{version}_linux_amd64.tar.gz",
        verified: "github.com/justanotherspy/shuck/"
    end
    on_arm do
      sha256 "0b83ef15111c36787bfd75406f11ffd236be802d9641cc302fdad486a0e477c6"
      url "https://github.com/justanotherspy/shuck/releases/download/v#{version}/shuck_#{version}_linux_arm64.tar.gz",
        verified: "github.com/justanotherspy/shuck/"
    end
  end

  name "shuck"
  desc "Print the exact failing CI step logs for a GitHub PR"
  homepage "https://github.com/justanotherspy/shuck"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "shuck"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/shuck"]
    end
  end

  # No zap stanza required

end
