# This file was generated by GoReleaser. DO NOT EDIT.
cask "sproot" do
  version "0.2.4"

  on_macos do
    on_intel do
      sha256 "7e098f1b92d6d366bda63432f7ac42ad318ea43d6218881c0426023f9660ab92"
      url "https://github.com/justanotherspy/sproot/releases/download/v#{version}/sproot_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/justanotherspy/sproot/"
    end
    on_arm do
      sha256 "e2b2342fd9fa585bbeb69370871306692af6b24450e97b914e0b5c4786f06244"
      url "https://github.com/justanotherspy/sproot/releases/download/v#{version}/sproot_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/justanotherspy/sproot/"
    end
  end

  on_linux do
    on_intel do
      sha256 "263b327effa74ad4b48eb197bc550d115d34980e487d21ecef3e702dc8f00a4b"
      url "https://github.com/justanotherspy/sproot/releases/download/v#{version}/sproot_#{version}_linux_amd64.tar.gz",
        verified: "github.com/justanotherspy/sproot/"
    end
    on_arm do
      sha256 "f1e2d852f7157bb8ae39503773da54c3f2bee76be79b22ef2cd1961b63c33289"
      url "https://github.com/justanotherspy/sproot/releases/download/v#{version}/sproot_#{version}_linux_arm64.tar.gz",
        verified: "github.com/justanotherspy/sproot/"
    end
  end

  name "sproot"
  desc "Bootstrap sprite.dev sprites from a user-owned config repo"
  homepage "https://github.com/justanotherspy/sproot"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sproot"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/sproot"]
    end
  end

  # No zap stanza required

end
