# This file was generated by GoReleaser. DO NOT EDIT.
cask "sproot" do
  version "0.2.3"

  on_macos do
    on_intel do
      sha256 "af28c948e286d15ecc9419b64dfaf26ae962b5ac3eec1dc0f3d3f70848b61a27"
      url "https://github.com/justanotherspy/sproot/releases/download/v#{version}/sproot_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/justanotherspy/sproot/"
    end
    on_arm do
      sha256 "9824f05863ee23e178fdcc7bd6ca60ded46e673fd4660a48e511f911fdc22849"
      url "https://github.com/justanotherspy/sproot/releases/download/v#{version}/sproot_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/justanotherspy/sproot/"
    end
  end

  on_linux do
    on_intel do
      sha256 "67d0bdcec2f80924788a97e5f4809a31ef8e03a00acdec939cf3cfc525f01f0d"
      url "https://github.com/justanotherspy/sproot/releases/download/v#{version}/sproot_#{version}_linux_amd64.tar.gz",
        verified: "github.com/justanotherspy/sproot/"
    end
    on_arm do
      sha256 "6d1793dce8ba774bacba7146eacbb307c1ca62c793ab9247c551addfd8b87bc3"
      url "https://github.com/justanotherspy/sproot/releases/download/v#{version}/sproot_#{version}_linux_arm64.tar.gz",
        verified: "github.com/justanotherspy/sproot/"
    end
  end

  name "sproot"
  desc "Bootstrap sprite.dev sprites from a user-owned config repo"
  homepage "https://github.com/justanotherspy/sproot"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sproot"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/sproot"]
    end
  end
end
