# This file was generated by GoReleaser. DO NOT EDIT.
cask "sproot" do
  version "0.2.5"

  on_macos do
    on_intel do
      sha256 "14a530c4de25e1106905425c1c7e2a227201e5a2a5f89e9d16c980e692cfaa13"
      url "https://github.com/justanotherspy/sproot/releases/download/v#{version}/sproot_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/justanotherspy/sproot/"
    end
    on_arm do
      sha256 "c6788f965178dd01836cd28d071d99889d890edc4503417236ebe168d0fcc4e2"
      url "https://github.com/justanotherspy/sproot/releases/download/v#{version}/sproot_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/justanotherspy/sproot/"
    end
  end

  on_linux do
    on_intel do
      sha256 "c8a2e581d3cdb0b4d43dcc41b6b707c1a44423fd6bbc6a089e820361be028721"
      url "https://github.com/justanotherspy/sproot/releases/download/v#{version}/sproot_#{version}_linux_amd64.tar.gz",
        verified: "github.com/justanotherspy/sproot/"
    end
    on_arm do
      sha256 "c2840af5a39d730102503c446c9b6812c37491c9623231ec5dd94a54aae1617b"
      url "https://github.com/justanotherspy/sproot/releases/download/v#{version}/sproot_#{version}_linux_arm64.tar.gz",
        verified: "github.com/justanotherspy/sproot/"
    end
  end

  name "sproot"
  desc "Bootstrap sprite.dev sprites from a user-owned config repo"
  homepage "https://github.com/justanotherspy/sproot"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sproot"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/sproot"]
    end
  end

  # No zap stanza required

end
